openapi: 3.0.0
info:
  title: monthConverter
  description: >-
    The name of the month that the number converts to
  version: 0.0.1
servers:
  - url: 'http://localhost:8080/day/{monthnumber}'
    description: Local dev server
paths:
  /day/{month number}:
  # Routes for GET 
    get:
      summary: The name of the month that the number converts to
      requestBody:
      responses:
        '201':
          description: name of month 
          content:
            application/json:
              schema:
                # we are referencing the month object definition found at the bottom of the file
                $ref: '#/components/schemas/day/{monthnumber}
        